name: 'Setup LaTeX'
description: 'Install TeX Live with XeLaTeX support'
runs:
  using: 'composite'
  steps:
    - name: Cache TeX Live
      uses: actions/cache@v4
      with:
        path: |
          /usr/share/texlive
          /usr/share/texmf
          /var/lib/texmf
        key: texlive-${{ runner.os }}-v2
    - name: Install TeX Live
      shell: bash
      run: |
        if ! command -v xelatex &> /dev/null; then
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-xetex \
            texlive-latex-extra \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            latexmk
        else
          echo "TeX Live already installed (from cache)"
        fi
